# Generated by Django 3.2.5 on 2024-10-09 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name="O'qtuvchi ism familyasi")),
                ('email', models.EmailField(max_length=254, verbose_name='emaili')),
                ('phone', models.CharField(max_length=20, verbose_name='telefon raqami')),
                ('image', models.ImageField(upload_to='uploads/teachers/%Y/%m/%d', verbose_name="o'qtuvchi rasmi")),
                ('body', models.TextField(verbose_name="o'qtuvchi haqida batafsil ma'lumot")),
                ('information', models.CharField(max_length=100, verbose_name="ma'lumoti")),
                ('experience_years', models.PositiveIntegerField()),
                ('subjects', models.ManyToManyField(to='common.Subject')),
            ],
        ),
    ]
